spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/blueprintdb
    username: blueprint
    password: secret3
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db-changelog.xml
    enabled: true
  security:
    oauth2:
      resourceserver:
          jwt:
            issuer-uri: http://localhost:9900/realms/blueprint

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:4200}

app:
  jwt:
    mapping:
      principal-claim-name: preferred_username
      authorities-claim-name: realm_access